# Generated by Django 2.1.1 on 2019-09-30 11:54

from django.db import migrations
from django.conf import settings


def add_perms(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    AOI = apps.get_model('geodata', 'AOI')
    aoi_ct = ContentType.objects.get_for_model(AOI)
    for city in settings.PORTAL_CITIES:
        name = 'Can view {0}'.format(city)
        codename = 'view_{0}'.format(city).lower()
        Permission.objects.create(
            name=name, content_type=aoi_ct, codename=codename)


def remove_perms(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    for city in settings.PORTAL_CITIES:
        codename = 'view_{0}'.format(city).lower()
        Permission.objects.filter(codename=codename).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_perms, remove_perms)
    ]
