# Generated by Django 2.1.11 on 2019-10-31 14:58

from django.db import migrations
from django.conf import settings
from django.contrib.auth.models import Group


def generate_superuser(apps, schema_editor):
    from apps.users.models import User

    superuser = User.objects.create_superuser(
        email=settings.ADMIN_USER_EMAIL,
        password=settings.ADMIN_USER_PASS,
        first_name='Admin',
        last_name='User')

    country = settings.PORTAL_INSTANCE
    admin_group = Group.objects.get(name='{0}AdminUserGroup'.format(country))
    gov_group = Group.objects.get(
        name='{0}GovernmentUserGroup'.format(country)
    )
    superuser.groups.add(admin_group)
    superuser.groups.add(gov_group)
    for city in settings.PORTAL_CITIES:
        name = '{0}UserGroup'.format(city)
        g = Group.objects.get(name=name)
        superuser.groups.add(g)

    superuser.save()


def remove_superuser(apps, schema_editor):
    from apps.users.models import User

    superuser = User.objects.get(first_name='Admin', last_name='User')
    superuser.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_groups'),
    ]

    operations = [
        migrations.RunPython(generate_superuser, remove_superuser)
    ]
