# Generated by Django 2.1.1 on 2019-07-26 09:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_auto_20190719_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(blank=True, help_text='Sector name', max_length=255, null=True)),
                ('barrio', models.CharField(blank=True, help_text='The name of the AOI.', max_length=255, null=True)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('manzana', models.IntegerField(blank=True, null=True)),
                ('coddane', models.CharField(blank=True, max_length=255, null=True)),
                ('ucg', models.IntegerField(blank=True, null=True)),
                ('loc', models.CharField(blank=True, max_length=255, null=True)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('long_mt', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='Block geometry', srid=4326)),
                ('aoi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='geodata.AOI')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='geodata.Sector')),
            ],
        ),
    ]
