# Generated by Django 2.1.1 on 2019-07-26 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_alter_block_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='geodata.Block'),
        ),
    ]
