# Generated by Django 2.1.1 on 2019-10-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='aoi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='geodata.AOI'),
        ),
        migrations.AddField(
            model_name='road',
            name='aoi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roads', to='geodata.AOI'),
        ),
    ]
