# Generated by Django 2.1.1 on 2019-10-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0010_add_greenspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='sv_key',
            field=models.CharField(blank=True, help_text='Mapillary API Start Key', max_length=255, null=True),
        ),
    ]
