# Generated by Django 2.1.1 on 2019-10-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0011_aoi_sv_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='sv_disaster',
            field=models.IntegerField(blank=True, help_text='Has disaster mitigation measure?', null=True),
        ),
    ]
