# Generated by Django 2.1.1 on 2019-10-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0012_alter_sv_disaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='subzone',
        ),
        migrations.RemoveField(
            model_name='building',
            name='zone',
        ),
    ]
