# Generated by Django 2.1.1 on 2019-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0014_remove_building_d_avg_height_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
