# Generated by Django 2.1.11 on 2019-10-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0019_alter_block_timestamped'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='sv_complet',
            field=models.CharField(blank=True, help_text='Is bulding completed?', max_length=255, null=True),
        ),
    ]
