# Generated by Django 2.1.11 on 2019-10-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0020_building_sv_complet'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='sv_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aoi',
            name='sv_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
