# Generated by Django 2.1.11 on 2019-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0022_standarise_id_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
