# Generated by Django 2.1.11 on 2019-11-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0024_buildingimage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='buildingimage',
            managers=[
            ],
        ),
    ]
