# Generated by Django 2.1.11 on 2019-11-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0025_update_images_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingimage',
            name='class_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buildingimage',
            name='confidence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
