# Generated by Django 2.1.11 on 2019-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0027_change_conf_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.CharField(blank=True, help_text='Original devseed block id', max_length=255, null=True),
        ),
    ]
