# Generated by Django 2.1.11 on 2019-11-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0028_alter_block_id_block'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aoi',
            index=models.Index(fields=['country'], name='geodata_aoi_country_b40342_idx'),
        ),
        migrations.AddIndex(
            model_name='aoi',
            index=models.Index(fields=['city'], name='geodata_aoi_city_222dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='aoi',
            index=models.Index(fields=['name'], name='geodata_aoi_name_efceb7_idx'),
        ),
        migrations.AddIndex(
            model_name='aoi',
            index=models.Index(fields=['sv_key'], name='geodata_aoi_sv_key_1ca302_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['block_id'], name='geodata_blo_block_i_5b162c_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['building_id'], name='geodata_bui_buildin_bf5299_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['d_material'], name='geodata_bui_d_mater_679df8_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['d_condition'], name='geodata_bui_d_condi_2f3d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['d_avg_height'], name='geodata_bui_d_avg_h_3a028a_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_design'], name='geodata_bui_sv_desi_c363e2_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_complet'], name='geodata_bui_sv_comp_dba904_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_materia'], name='geodata_bui_sv_mate_d75b67_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_use'], name='geodata_bui_sv_use_9d9d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_condit'], name='geodata_bui_sv_cond_4a9545_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_window'], name='geodata_bui_sv_wind_8edfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_door'], name='geodata_bui_sv_door_5f6959_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_garage'], name='geodata_bui_sv_gara_93fb17_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['hz_earthqu'], name='geodata_bui_hz_eart_2e9917_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['hz_landslide'], name='geodata_bui_hz_land_6be5af_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['hz_flood'], name='geodata_bui_hz_floo_f87303_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['hz_wind'], name='geodata_bui_hz_wind_1d0411_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['count'], name='geodata_bui_count_08026f_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['pt_avg'], name='geodata_bui_pt_avg_f872f4_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['pt_sum'], name='geodata_bui_pt_sum_e80be7_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['pt_avg_owed'], name='geodata_bui_pt_avg__c2c4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['pt_sum_owed'], name='geodata_bui_pt_sum__234548_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['tot_qualit'], name='geodata_bui_tot_qua_2e4b54_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['soft_story'], name='geodata_bui_soft_st_827226_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['value'], name='geodata_bui_value_a308c5_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['dem_reset'], name='geodata_bui_dem_res_95e303_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['dem_struct'], name='geodata_bui_dem_str_213e28_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['dem_qualit'], name='geodata_bui_dem_qua_25ca1a_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['dem_both'], name='geodata_bui_dem_bot_f5c543_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['dem_insur'], name='geodata_bui_dem_ins_d4f1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['dem_micro'], name='geodata_bui_dem_mic_5c8a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['opp_expansion'], name='geodata_bui_opp_exp_117d62_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['cap_payment'], name='geodata_bui_cap_pay_421034_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingimage',
            index=models.Index(fields=['detection_id'], name='geodata_bui_detecti_46bd4b_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingimage',
            index=models.Index(fields=['image_id'], name='geodata_bui_image_i_2b49b4_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingimage',
            index=models.Index(fields=['angle'], name='geodata_bui_angle_31aa3a_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingimage',
            index=models.Index(fields=['confidence'], name='geodata_bui_confide_f188dd_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingimage',
            index=models.Index(fields=['class_str'], name='geodata_bui_class_s_89d1be_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingimage',
            index=models.Index(fields=['subfolder'], name='geodata_bui_subfold_d505be_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingimage',
            index=models.Index(fields=['frame'], name='geodata_bui_frame_d47f93_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingimage',
            index=models.Index(fields=['cam'], name='geodata_bui_cam_19441a_idx'),
        ),
        migrations.AddIndex(
            model_name='greenspace',
            index=models.Index(fields=['type'], name='geodata_gre_type_6be1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='greenspace',
            index=models.Index(fields=['area_km'], name='geodata_gre_area_km_3ddcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='road',
            index=models.Index(fields=['surface'], name='geodata_roa_surface_6d49f5_idx'),
        ),
        migrations.AddIndex(
            model_name='road',
            index=models.Index(fields=['condition'], name='geodata_roa_conditi_a11c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='road',
            index=models.Index(fields=['width_m'], name='geodata_roa_width_m_e3abf8_idx'),
        ),
        migrations.AddIndex(
            model_name='road',
            index=models.Index(fields=['length_m'], name='geodata_roa_length__c46210_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['name'], name='geodata_sec_name_b3553a_idx'),
        ),
    ]
