# Generated by Django 2.1.11 on 2019-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0029_create_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='sv_vintage',
            field=models.IntegerField(blank=True, help_text='Vintage of construction.', null=True),
        ),
    ]
