# Generated by Django 2.1.11 on 2020-01-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0030_alter_sv_vintage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['address'], name='geodata_bui_address_634388_idx'),
        ),
    ]
