# Generated by Django 2.1.11 on 2020-01-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0031_index_building_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['land_publi'], name='geodata_bui_land_pu_24fdd3_idx'),
        ),
    ]
