# Generated by Django 2.1.11 on 2020-01-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0032_index_land_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='sector_id',
            field=models.CharField(blank=True, help_text='Unique sector id', max_length=255, null=True),
        ),
    ]
