# Generated by Django 2.1.11 on 2020-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0034_buildingimage_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingimage',
            name='lat',
            field=models.FloatField(blank=True, help_text='Image latitude.', null=True),
        ),
        migrations.AddField(
            model_name='buildingimage',
            name='lon',
            field=models.FloatField(blank=True, help_text='Image longitude.', null=True),
        ),
    ]
