# Generated by Django 2.1.11 on 2020-01-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0036_alter_sv_vintage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidenceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_str', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confidence_values', to='geodata.Building')),
            ],
        ),
        migrations.AddIndex(
            model_name='confidencevalue',
            index=models.Index(fields=['class_str'], name='geodata_con_class_s_2152ef_idx'),
        ),
        migrations.AddIndex(
            model_name='confidencevalue',
            index=models.Index(fields=['confidence'], name='geodata_con_confide_52b5ce_idx'),
        ),
    ]
