# Generated by Django 2.1.11 on 2020-01-20 11:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0038_confidencevalue_aoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidencevalue',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='confidencevalue',
            name='confidence',
            field=models.FloatField(blank=True, help_text='Average confidence value.', null=True),
        ),
    ]
