# Generated by Django 2.1.11 on 2020-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0039_add_confidenc_geom'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='greenspace',
            name='geodata_gre_area_km_3ddcdd_idx',
        ),
        migrations.RemoveField(
            model_name='greenspace',
            name='area_km',
        ),
        migrations.AddField(
            model_name='greenspace',
            name='area_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='greenspace',
            index=models.Index(fields=['area_m'], name='geodata_gre_area_m_b34304_idx'),
        ),
    ]
