# Generated by Django 2.1.11 on 2020-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0040_alter_greenspace_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='count',
            field=models.IntegerField(blank=True, default=0, help_text='Number of records calculated in\n            average property tax per building', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='pt_avg',
            field=models.IntegerField(blank=True, default=0, help_text='Average property tax per building', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='pt_avg_owed',
            field=models.IntegerField(blank=True, default=0, help_text='Average property tax owed per building', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='pt_sum',
            field=models.IntegerField(blank=True, default=0, help_text='Sum of property tax per building', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='pt_sum_owed',
            field=models.IntegerField(blank=True, default=0, help_text='Sum of property tax owed per building', null=True),
        ),
    ]
