# Generated by Django 2.2.12 on 2020-05-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0047_add_block_k3_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='k3',
            field=models.FloatField(blank=True, help_text='Block level Covid Vulnerabilty Index', null=True),
        ),
    ]
