# Generated by Django 2.2.12 on 2020-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0048_building_k3'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='building',
            name='geodata_bui_buildin_bf5299_idx',
        ),
        migrations.RemoveField(
            model_name='building',
            name='building_id',
        ),
        migrations.AddField(
            model_name='building',
            name='uid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['uid'], name='geodata_bui_uid_112298_idx'),
        ),
    ]
