# Generated by Django 2.2.12 on 2020-07-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0050_building_image_cam_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['d_slope'], name='geodata_bui_d_slope_71ad22_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['d_volume'], name='geodata_bui_d_volum_527729_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['d_area'], name='geodata_bui_d_area_2cf38a_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_constru'], name='geodata_bui_sv_cons_25420a_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_vintage'], name='geodata_bui_sv_vint_6a7711_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_securit'], name='geodata_bui_sv_secu_c85495_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['sv_disaster'], name='geodata_bui_sv_disa_2f4d96_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['park'], name='geodata_bui_park_e02e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['infrastruc'], name='geodata_bui_infrast_ea8bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['land_servi'], name='geodata_bui_land_se_e1ea7f_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['k3'], name='geodata_bui_k3_480539_idx'),
        ),
    ]
