# Generated by Django 2.2.12 on 2020-07-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0052_add_building_geohash'),
        ('geodata', '0051_confidencevalue_bucket'),
    ]

    operations = [
    ]
