# Generated by Django 2.2.12 on 2020-08-07 14:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0053_mergemigrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='extra_attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Unstructured extra data, eg survey data.', null=True),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['extra_attrs'], name='geodata_bui_extra_a_83b16a_idx'),
        ),
    ]
