# Generated by Django 2.2.12 on 2021-01-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0057_remove_unused_building_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['hz_tsunami'], name='geodata_bui_hz_tsun_64cf37_idx'),
        ),
    ]
